language: go
os:
  - linux
  - windows
go:
  - 1.x
  - 1.7.x
  - master
sudo: false
before_script:
  - go get -t -v ./...
script:
  - go build
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
notifications:
  email: false